name: Update Markdown from Google Sheets

on:
  schedule:
    - cron: '0 12 * * *'  # Runs once a day at 12:00 PM UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-markdown:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Use Python 3.x or preferred version

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Fetch data from Google Sheets and create markdown files
      env:
        GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
        GOOGLE_SHEETS_ID: ${{ secrets.GOOGLE_SHEETS_ID }}
      run: python scripts/fetch_sheets_data.py

    - name: Commit changes
      run: |
        git config --local user.email "weh9000@gmail.com"   # Your GitHub email
        git config --local user.name "GitHub Action"        # You can replace with your GitHub username or keep GitHub Action
        git add _people/* || true                          # Add the new files in _people
        git add last_processed.txt || true                 # Add the updated last_processed.txt file
        git commit -m "Update markdown with new Google Sheets data" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/UK-NABES/UK-NABES.github.io.git || echo "Nothing to push"
