name: Update Markdown from Google Sheets

on:
  schedule:
    - cron: '0 12 * * *'  # Runs once per day at noon
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-markdown:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Use Python 3.x or any preferred version

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Fetch data from Google Sheets and create markdown files
      env:
        GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
        GOOGLE_SHEETS_ID: ${{ secrets.GOOGLE_SHEETS_ID }}
      run: python scripts/fetch_sheets_data.py
      
    - name: Commit changes
      run: |
        git config --local user.email "your-email@example.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update markdown with new Google Sheets data"
        git push
